name: "Tzeract Issue"
description: "Suggest a new feature or enhancement"
title: "Feature: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## Tzeract Issue Request Form
        Please fill out the following sections with as much detail as you can.

  - type: input
    id: motivation
    attributes:
      label: "1. Motivation"
      description: "Explain who or what prompted this feature request. What's the underlying need?"
      placeholder: "This request came from XXX to improve..."

  - type: textarea
    id: intended_outcome
    attributes:
      label: "2. Intended Outcome"
      description: "What does success look like for this feature?"
      placeholder: "When implemented, it will..."

  - type: textarea
    id: description
    attributes:
      label: "3. Steps"
      description: "If currently known, write the different steps."
      placeholder: "Step 1: ...."

  - type: textarea
    id: consequences
    attributes:
      label: "4. Consequences"
      description: "List any other services or repositories that will be affected by this feature."
      placeholder: "Requires changes in..."

  - type: textarea
    id: additional_context
    attributes:
      label: "(Optional) Additional Context"
      description: "Add any extra details that might help."
      render: yaml  # or 'plaintext' if you prefer
      placeholder: |
        # Extra material
        - Links

